baseURL = "/"
languageCode = "en-us"
title = "ACA Entities"
showToc = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]

[markup]
  [markup.tableOfContents]
    ordered = false

[markup.goldmark.renderer]
unsafe = true

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
