---
AllCops:
  NewCops: enable

Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/EmptyLinesAroundArguments:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
