# frozen_string_literal: true

# Include the baseline entities and types
module AcaEntities
  module Libraries
    module CoreLibrary

      require 'aca_entities/types'
      require 'aca_entities/contracts/contract'
      require 'aca_entities/contracts/timestamp_contract'
      require 'aca_entities/contracts/currency_contract'
      require 'aca_entities/contracts/identifiers/identifier_kind_contract'
      require 'aca_entities/contracts/identifiers/id_contract'
      require 'aca_entities/contracts/people/person_reference_contract'
      require 'aca_entities/contracts/households/household_reference_contract'
      require 'aca_entities/contracts/households/coverage_household_reference_contract'
      require 'aca_entities/contracts/families/family_reference_contract'
      require 'aca_entities/contracts/families/family_member_reference_contract'
      require 'aca_entities/contracts/organizations/issuer_profile_reference_contract'
      require 'aca_entities/contracts/products/product_reference_contract'
      require 'aca_entities/contracts/organizations/general_agency_reference_contract'
      require 'aca_entities/contracts/organizations/broker_agency_profile_reference_contract'
      require 'aca_entities/contracts/brokers/broker_role_reference_contract'
      require 'aca_entities/contracts/brokers/broker_account_contract'
      require 'aca_entities/contracts/brokers/broker_role_contract'
      require 'aca_entities/contracts/general_agencies/general_agency_account_contract'
      require 'aca_entities/contracts/qualifying_life_events/qualifying_life_event_kind_reference_contract'
      require 'aca_entities/contracts/enrollment_periods/special_enrollment_period_contract'
      require 'aca_entities/contracts/enrollment_periods/special_enrollment_period_reference_contract'
      require 'aca_entities/contracts/enrollments/hbx_enrollment_exemption_contract'
      require 'aca_entities/contracts/enrollments/hbx_enrollment_member_contract'
      require 'aca_entities/contracts/enrollments/hbx_enrollment_reference_contract'
      require 'aca_entities/contracts/enrollments/hbx_enrollment_contract'
      require 'aca_entities/contracts/households/coverage_household_member_contract'
      require 'aca_entities/contracts/households/coverage_household_contract'
      require 'aca_entities/contracts/financial/payment_transactions/payment_transaction_contract'
      require 'aca_entities/contracts/locations/address_contract'
      require 'aca_entities/contracts/contacts/phone_contact_contract'
      require 'aca_entities/contracts/contacts/email_contact_contract'
      require 'aca_entities/contracts/people/person_name_contract'
      require 'aca_entities/contracts/people/person_relationship_contract'
      require 'aca_entities/contracts/people/person_health_contract'
      require 'aca_entities/contracts/people/person_demographics_contract'
      require 'aca_entities/contracts/people/person_contract'
      require 'aca_entities/contracts/households/household_contract'
      require 'aca_entities/contracts/families/family_member_contract'
      require 'aca_entities/contracts/families/family_contract'

      # entities
      require 'aca_entities/timestamp'
      require 'aca_entities/currency'
      require 'aca_entities/identifiers/identifier_kind'
      require 'aca_entities/identifiers/id'
      require 'aca_entities/organizations/issuer_profile_reference'
      require 'aca_entities/products/product_reference'
      require 'aca_entities/people/person_reference'
      require 'aca_entities/households/household_reference'
      require 'aca_entities/households/coverage_household_reference'
      require 'aca_entities/families/family_reference'
      require 'aca_entities/families/family_member_reference'
      require 'aca_entities/organizations/general_agency_reference'
      require 'aca_entities/organizations/broker_agency_profile_reference'
      require 'aca_entities/brokers/broker_role_reference'
      require 'aca_entities/brokers/broker_account'
      require 'aca_entities/brokers/broker_role'
      require 'aca_entities/general_agencies/general_agency_account'
      require 'aca_entities/qualifying_life_events/qualifying_life_event_kind_reference'
      require 'aca_entities/enrollment_periods/special_enrollment_period'
      require 'aca_entities/enrollment_periods/special_enrollment_period_reference'
      require 'aca_entities/enrollments/hbx_enrollment_exemption'
      require 'aca_entities/enrollments/hbx_enrollment_member'

      require 'aca_entities/enrollments/hbx_enrollment_reference'
      require 'aca_entities/enrollments/hbx_enrollment'
      require 'aca_entities/households/coverage_household_member'
      require 'aca_entities/households/coverage_household'
      require 'aca_entities/financial/payment_transactions/payment_transaction'
      require 'aca_entities/locations/address'
      require 'aca_entities/contacts/phone_contact'
      require 'aca_entities/contacts/email_contact'
      require 'aca_entities/people/person_name'
      require 'aca_entities/people/person_relationship'
      require 'aca_entities/people/person_health'
      require 'aca_entities/people/person_demographics'
      require 'aca_entities/people/person'
      require 'aca_entities/households/household'
      require 'aca_entities/families/family_member'
      require 'aca_entities/families/family'

      require 'aca_entities/operations/yaml/deserialize'
    end
  end
end
