name: Doc Generation
on: push

jobs:
  docs_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: install hugo
        run: sudo snap install hugo --channel=extended
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v2-${{ runner.os }}-gems-aca_entities-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v2-${{ runner.os }}-gems-aca_entities-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: Install project gems
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run yard
        run: bundle exec yard && cp -rf ./doc ./hugo/static/
      - run: cd hugo && npm install && hugo --minify
