name: Documentation
on: push

jobs:
  docsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install hugo
        run: |
          sudo snap install hugo --channel=extended
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7.6-aca_entities-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            ${{ runner.os }}-2.7.6-aca_entities-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: npm install
        run: |
          cd hugo && npm install
      - name: Generate Documentation
        run: |
          bundle exec rake docsite
      - name: Generate Doc Artifact
        run: |
          cd hugo/public && zip -r site.zip ./*
      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: hugo/public/site.zip
